<?php
	// ================================================
	// PHP image manager - iManager 
	// ================================================
	// iManager English dialog
	// ================================================
	// Developed: net4visions.com
	// Copyright: net4visions.com
	// License: LGPL - see license.txt
	// (c)2005 All rights reserved.
	// ================================================
	// Revision: 1.0                   Date: 05/06/2005
	// ================================================
	
	//-------------------------------------------------------------------------
	// charset to be used in dialogs
	$lang_charset = 'UTF-8';
	// text direction for the current language to be used in dialogs
	$lang_direction = 'ltr';
	//-------------------------------------------------------------------------
	
	// language text data array
	// first dimension - block, second - exact phrase
	//-------------------------------------------------------------------------
	// iManager
	$lang_data = array (  
		'imanager' => array (
		//-------------------------------------------------------------------------
		// common - im
		'im_001' => 'Administrador de imágenes',
		'im_002' => 'Imágenes',
		'im_003' => 'Menú',
		'im_004' => 'Bienvenido',
		'im_005' => 'Insertar',
		'im_006' => 'Cancelar',
		'im_007' => 'Insertar',		
		'im_008' => 'Inserte/cambie imagen',
		'im_009' => 'Propiedades',
		'im_010' => 'Propiedades de la imagen',
		'im_011' => 'Herramientas',
		'im_012' => 'Herramientas de imagen',
		'im_013' => 'Subventana',
		'im_014' => 'Subventana',
		'im_015' => 'Acerca de',
		'im_016' => 'Sección',				
		'im_096' => 'Espere mientras carga...',
		'im_097' => 'Click para cambiar de color',
		'im_098' =>	'Abrir sección',
		'im_099' => 'Cerrar sección',
		//-------------------------------------------------------------------------
		// insert/change screen - in	
		'in_001' => 'Inserte/cambie imagen',
		'in_002' => 'Biblioteca',
		'in_003' => 'Selecione una bibliteca',
		'in_004' => 'Imágenes',
		'in_005' => 'Vista previa',
		'in_006' => 'Borrar imagen',
		'in_007' => 'Click para una vista más grande de la imagen',
		'in_008' => 'Abra una sección para subir/renombrar o borrar una imagen.',	
		'in_009' => 'Información',
		'in_010' => 'Subventana',
		'in_013' => 'Crear un enlace de la imagen para abrir en otra ventana.',
		'in_014' => 'Quitar enlace a subventana',	
		'in_015' => 'Archivo',	
		'in_016' => 'Renombrar',
		'in_017' => 'Renombrar imagen',
		'in_018' => 'Subir',
		'in_019' => 'Subir imagen',	
		'in_020' => 'Tamaño(s)',
		'in_021' => 'Marque el/los tamaño(s) a los cuales se redimencionará(n) la(s) imagen(es)',
		'in_022' => 'Original',
		'in_023' => 'La imagen será recortada',
		'in_024' => 'Borrar',
		'in_025' => 'Carpeta',
		'in_026' => 'Click para crear carpeta',
		'in_027' => 'Crear carpeta',
		'in_028' => 'Ancho',
		'in_029' => 'Altura',
		'in_030' => 'Tipo',
		'in_031' => 'Tamaño',
		'in_032' => 'Mombre',
		'in_033' => 'Creada',
		'in_034' => 'Modificada',
		'in_035' => 'Información de la imagen',
		'in_036' => 'Click en la imagen para cerrar ventana',	
		'in_037' => 'Click para cambiar el modo de vista',		
		'in_099' => 'por defecto',	
		//-------------------------------------------------------------------------
		// properties, attributes - at
		'at_001' => 'Atributos de la imagen',
		'at_002' => 'Origen',
		'at_003' => 'Título',
		'at_004' => 'TITULO - muestra la descripcion de la imagen cuando el mouse este encima',
		'at_005' => 'Descripción',
		'at_006' => 'ALT -  texto de reemplazo de la imagen si no carga ésta',
		'at_007' => 'Estilo',
		'at_008' => 'asegúrese que el estilo exista en la hoja de estilos!',
		'at_009' => 'estilo CSS',	
		'at_010' => 'Atributos',
		'at_011' => 'Los atributos "align", "border", "hspace", y "vspace" de la imagen no sobn soportados in XHTML 1.0 Strict DTD. Use Estilo-CSS en cambio.',
		'at_012' => 'Alineación',	
		'at_013' => 'Por defecto',
		'at_014' => 'izquierda',
		'at_015' => 'derecha',
		'at_016' => 'arriba',
		'at_017' => 'medio',
		'at_018' => 'abajo',
		'at_019' => 'centro absoluto',
		'at_020' => 'línea superior',
		'at_021' => 'línea base',		
		'at_022' => 'Tamaño',
		'at_023' => 'Ancho',
		'at_024' => 'Altura',
		'at_025' => 'Borde',
		'at_026' => 'V-espacio',
		'at_027' => 'H-espacio',
		'at_028' => 'Vista previa',	
		'at_029' => 'Click to enter special character into title field',
		'at_030' => 'Click to enter special character into description field',
		'at_031' => 'Reset image dimensions to default values',
		'at_032' => 'Leyenda',
		'at_033' => 'marcada: defina la leyenda de la imagen / sin marca: sin leyenda de imagen o quite la existente',
		'at_034' => 'defina la leyenda de la imagen',
		'at_099' => 'por defecto',	
		//-------------------------------------------------------------------------
		//------------------------------------------------ -------------------------
// Caja de herramientas - TB
		'tb_001' => 'Salida',
		'tb_002' => 'Redimencion',
		'tb_003' => 'Recortar',
		'tb_004' => 'Orientación',
		'tb_005' => 'Filtros',
		// 'tb_006' => 'texto dinámico ",
		'tb_007' => 'Marca de agua',
		'tb_008' => 'Mascara',
		'tb_009' => 'Asistente',
		'tb_010' => 'Ver configuración actual',
		'tb_011' => 'Fuente',
		'tb_012' => 'Información',
		'tb_013' => 'Destino',
		'tb_014' => 'Archivo',
		'tb_015' => 'Si está marcado (ajuste predeterminado, entonces la miniatura se representará en un fichero. De lo contrario miniatura se creará de forma dinámica.',
		'tb_016' => 'Sobreescribir',
		'tb_017' => 'Si está marcada, los cambios de caja de herramientas se aplicarán a la imagen existente - la imagen original se sobrescribe! Si no se controla, los cambios de caja de herramientas se aplicarán y guardar en un archivo de imagen. ',
		'tb_018' => 'Formato',
		'tb_019' => 'Por favor seleccione el formato de imagen deseado - (por defecto: JPEG)',
		'tb_020' => 'calidad',
		'tb_021' => 'en miniatura',
		'tb_022' => 'Si se marca, la imagen en miniatura será actualizada. De lo contrario, se creará una nueva!',
		'tb_023' => 'Actualizar',
		'tb_024' => 'Vista previa',
		'tb_025' => 'Haz clic aquí para ver la imágenes de tamaño superior at tamaño de vista previa',
		'tb_026' => 'Superposición / subyacente',
		'tb_096' => 'Aplicar cambios a la caja de herramientas de imagen - Actualización ventana de vista previa',
		'tb_097' => 'Guardar cambios de la caja de herramientas - Actualización de archivo de imagen',
		'tb_098' => 'Actualizar',
		'tb_099' => 'Aceptar',
		//------------------------------------------------ -------------------------
		// Cambiar el tamaño - RS
		'rs_001' => 'Tamaño',
		'rs_002' => 'Tamaño',
		'rs_003' => 'Ancho',
		'rs_004' => 'Altura',
		'rs_005' => 'Haga clic para reeestablecer las dimensiones',
		'rs_006' => 'Dimensiones',
		'rs_007' => 'Mantener',
		'rs_008' => 'Mantener relación de aspecto - proporcion de la imagen no se modifica.',
		'rs_009' => 'Mantener relación de aspecto',
		'rs_010' => 'Ignorar',
		'rs_011' => 'No haga caso de proporciones - el cambio de tamaño proporcional desactivar y estirar la imagen para ajustarse a valores de ancho y altura - esto puede conducir a una distorsión de la imagen.',
		'rs_012' => 'ignorar la relación de aspecto',
		'rs_013' => 'Grupo',
		'rs_014' => 'Mantener proporción',
		'rs_015' => 'Mantener proporción - mantiene las proporciones de la imagen y crea una imagen en miniatura de tamaño fijo!',
		'rs_016' => 'Color',
		'rs_017' => 'Recortar',
		'rs_018' => 'Auto recorte',
		'rs_019' => 'Auto recorte, ajustara el conteniido a la menor dimención.',
		'rs_020' => 'Ampliar',
		'rs_021' => 'Permitir ampliación',
		'rs_022' => 'Permitir la ampliación de la imagen - esto puede conducir a una distorsión de la imagen!',
		'rs_099' => 'por defecto',
		//------------------------------------------------ -------------------------
		// Interfaz derecorte - ci
		'ci_001' => 'Interfaz recorte',
		'ci_002' => 'Utilice el boton "shift " o "Ctrl " para cambiar el tamaño del campo',
		'ci_003' => 'Reestablecer interfaz',
		'ci_004' => 'Previsualizar superficie recortada',
		'ci_005' => 'Cerrar interfaz',
		//------------------------------------------------ -------------------------
		// recorte - CR
		'cr_001' => 'Recortar',
		'cr_002' => 'Recortar',
		'cr_003' => 'Abrir interfaz de recorte',
		'cr_004' => 'Cerrar interfaz de recorte',
		'cr_005' => 'Interfaz de recorte - o bien introduzca los valores manualmente o utilice la interface. Si esta utilizando la interface de recorte utilíce los botones"Shift " o "Ctrl " para cambiar el tamaño del área recorte',
		'cr_006' => 'Ancho',
		'cr_007' => 'Altura',
		'cr_008' => 'Arriba',
		'cr_009' => 'Izquierda',
		'cr_010' => 'relación',
		'cr_011' => 'Establecer la relación del area de recorte (por defecto: 4: 3)',
		'cr_012' => 'ninguno',
		'cr_099' => 'por defecto',
		//------------------------------------------------ -------------------------
// Orientación - o
		'or_001' => 'Orientación',
		'or_002' => 'Orientación',
		'or_003' => 'Use "voltear" o "rotar" para cambiar la orientación de la imagen ',
		'or_004' => 'Voltear',
		'or_005' => 'horizontal',
		'or_006' => 'vertical',
		'or_007' => 'Ambos',
		'or_008' => 'Rotar',
		'or_009' => 'Si se pone a "EXIF", la orientación almacenada por la cámara se utilizará',
		'or_010' => 'Angulo',
		'or_011' => 'Rotación por ángulo: ángulo de rotación en grados; positivos = izquierda, negativo = derecha',
		'or_012' => 'Auto',
		'or_013' => 'Rotación automática: conjunto de datos Exif, para utilizar la orientación EXIF almacenada por la cámara. También se puede configurar a +180 ° o -180 ° para paisaje, o +90 ° o -90 ° para retrato. Los valores positivos para los valores de las agujas del reloj y negativo para la izquierda.',
		'or_014' => '+ 90 °',
		'or_015' => '- 90 °',
		'or_016' => '+ 180 °',
		'or_017' => '- 180 °',
		'or_018' => 'datos Exif',
		'or_019' => 'Color',
		'or_020' => 'retrato',
		'or_021' => 'paisaje',
		'or_022' => 'cámara',
		'or_099' => 'por defecto',
		//------------------------------------------------ -------------------------
		// Colorear - co
		'co_001' => 'Filtros',
		'co_002' => 'Filtros',
		'co_003' => 'Filtros - aplicar filtros a la imagen',
		'co_004' => 'Efectos',
		'co_005' => 'Efectos - aplicar colores a la imagen',
		'co_006' => 'Retoque',
		'co_007' => 'Retoque - mejorar la calidad de la imagen',
		//------------------------------------------------ -------------------------
		// Efectos - EF
		'ef_001' => 'Efectos',
		'ef_002' => 'Efectos',
		'ef_003' => 'Escala de grises',
		'ef_099' => 'por defecto',
		'ef_004' => 'negativas',
		'ef_005' => 'B & N',
		'ef_006' => 'Sepia',
		'ef_007' => 'Sepia - sepia es utilizado por los fotógrafos a crear un tono más cálido de impresión. Tonos sepia le da a su imagen una sensación antigua.',
		'ef_008' => 'Intensidad',
		'ef_009' => 'Color',
		'ef_010' => 'Color - colorear la imagen',
		'ef_011' => 'Intensidad',
		//------------------------------------------------ -------------------------
		// Retoque - para
		'to_001' => 'Retoque',
		'to_002' => 'Retoque',
		'to_003' => 'Gamma',
		'to_004' => 'Saturación',
		'to_005' => 'Mascara',
		'to_006' => 'Filtros de enfocado realzan los bordes, o las diferencias entre la luz y la sombrao y puntos de muestra en una imagen. El filtro Máscara de enfoque tiene parámetros que permiten sólo afectar los bordes de la imagen, y para excluir zonas de bajo contraste.',
		'to_007' => 'máscara de desenfoque',
		'to_008' => 'Radio',
		'to_009' => 'Radio controla el ancho del borde.',
		'to_010' => 'Cantidad',
		'to_011' => 'Cantidad es como un control de volumen, exagerando las diferencias de borde. Monto interactúa con Radio como a nivel de nitidez, pero no afecta a la anchura de los bordes de punta. Monto tiene un gran efecto, y los valores de 80 a 120 son normalmente utilizable si el Radio "t demasiado grande.',
		'to_012' => 'Umbral',
		'to_013' => 'Umbral de valores tonales especifica a qué distancia adyacente tienen que ser (valores de 0 .. 255) antes que el filtro se aplique a los bordes.',
		'to_014' => 'Nivel',
		'to_015' => 'Contraste automático',
		'to_016' => 'Nivel - esta función es similar a la función de ajuste automático de contraste en Adobe Photoshop',
		'to_017' => 'Canal',
		// 'to_018' => '',
		'to_019' => 'todos',
		'to_020' => 'rojo',
		'to_021' => 'verde',
		'to_022' => 'azul',
		'to_023' => 'min.',
		// 'to_024' => '',
		'to_025' => 'Max.',
		// 'to_026' => '',
		'to_027' => 'auto',
		'to_028' => 'Desenfoque',
		'to_029' => 'desenfoque suaviza el enfoque de la imagen seleccionada.',
		'to_030' => 'Balance',
		'to_031' => 'el balance de blancos',
		'to_032' => 'Balance - el filtro intenta mantener el brillo por lo que cualquier color gris, teóricamente, puede ser utilizado.',
		'to_098' => 'de fondo - sólo si jpeg',
		'to_099' => 'por defecto',
//------------------------------------------------ -------------------------
// Marca de agua - wm
		'wm_001' => 'Marca de agua',
		'wm_002' => 'Marca de agua añade a la imágen "texto" o "foto" como marca de agua',
		'wm_003' => 'Añadir',
		'wm_004' => 'Tipo',
		'wm_005' => 'texto',
		'wm_006' => 'imagen',
		'wm_007'=> 'Seleccione el tipo de marca de agua que debe aplicarse a la imagen ',
		'wm_008' => 'Texto',
		'wm_009' => 'Introduzca el texto de marca de agua que se aplicará a la imagen',
		'wm_010' => 'Haga clic para entrar carácter especial en el campo de texto',
		'wm_011' => 'Color',
		'wm_012' => 'Tipo de letra',
		'wm_013' => 'sistema',
		'wm_014' => 'tipo verdadero',
		'wm_015' => 'Seleccione una fente pre-instalada o la fuente true-type',
		'wm_016' => 'Fuente',
		'wm_017' => 'Tamaño',
		'wm_018' => 'Angulo',
		'wm_019' => 'Opacidad',
		'wm_020' => 'Margen',
		'wm_021' => 'Alineación',
		'wm_022' => 'arriba-izquieda',
		'wm_023' => 'ariba',
		'wm_024' => 'derecha-arriba',
		'wm_025' => 'izquierda',
		'wm_026' => 'derecha',
		'wm_027' => 'abajo-izquierda',
		'wm_028' => 'abajo',
		'wm_029' => 'abajo-derecha',
		'wm_030' => 'mosaico',
		'wm_031' => 'color de texto',
		'wm_032' => 'Fuente',
		'wm_099' => 'por defecto',
		//------------------------------------------------ -------------------------
		// Superposición - OV
		'ov_001' => 'Superposición',
		'ov_002' => 'Superposición',
		'ov_003' => 'Superposición - superposiciones de una imagen en la imagen en miniatura, o superposiciones de la imagen en otra imagen.',
		'ov_004' => 'Organizar',
		'ov_005' => 'Traer al frente',
		'ov_006' => 'Enviar al fondo',
		'ov_007' => 'Organizar - Si se pone a "Traer al frente", la superposición de imágenes se establecerá en la parte superior de la imagen (por defecto). Si se establece a "Enviar al fondo", su imagen se creará en la parte superior de la imagen superpuesta.',
'ov_008' => 'Opacidad',
		'ov_009' => 'Margen',
		'ov_010' => 'Biblioteca',
		'ov_099' => 'Por defecto',
		//------------------------------------------------ -------------------------
		// Máscara - MS
		'ms_001' => 'Mascara',
		'ms_002' => 'La máscara de la imagen',
		'ms_003' => 'Con el uso de las máscaras debajo se puede crear algunas imágenes de aspecto realmente fantástico',
		'ms_004' => 'Color',
		'ms_099' => 'Por defecto',
		//------------------------------------------------ -------------------------
		// Asistente de imagen - WZ
		'wz_001' => 'Asistente',
		'wz_002' => 'Asistente de la imagen',
		'wz_003' => 'Asistente de la imagen - le permite añadir algunos efectos especiales como el bisel, marcos, sombras, bordes, esquinas curvas, y la elipse',
		'wz_004' => 'Biselado',
		'wz_005' => 'Biselado - para añadir el efecto de elevado o hundido a la imagen. La anchura del bisel es variable como los colores.',
		'wz_006' => 'Marco',
		'wz_007' => 'Marco ',
		'wz_008' => 'Sombras',
		'wz_009' => 'Sombra - un efecto de sombra se desvanece a partir de los bordes de la imagen.',
		'wz_010' => 'Borde',
		'wz_011' => 'Borde curvo. Las variables se utilizan para el radio de punta, el color de fondo y ancho del borde.',
		'wz_012' => 'Esquina',
		'wz_013' => 'esquina curva - se utiliza para tomar la dureza fuera de la imagen rectangular. Las variables se utilizan para el radio de punta, el color de fondo y el ancho.',
		'wz_014' => 'Elipse',
		'wz_015' => 'Elipse - Se utiliza una variable para el color de fondo.',
		'wz_099' => 'default',
		//------------------------------------------------ -------------------------
		// Bisel - se
		'be_001' => 'Biselado',
		'be_002' => 'Biselado',
		'be_003' => 'Ancho',
		'be_004' => 'Light',
		'be_005' => 'Arriba, a la izquierda',
		'be_006' => 'Dark',
		'be_007' => 'abajo, derecha',
		//------------------------------------------------ -------------------------
		// Frame - FR
		'fr_001' => 'Marco',
		'fr_002' => 'Marco',
		'fr_003' => 'borde',
		'fr_004' => 'ancho del borde',
		'fr_005' => 'biselado',
		'fr_006' => 'Ancho de bisel',
		'fr_007' => 'principal',
		'fr_008' => 'marco principal',
		'fr_009' => 'biselado',
		'fr_010' => 'bisel destacado',
		'fr_011' => 'Sombras',
		'fr_012' => 'bisel sombra',
		//------------------------------------------------ -------------------------
		// Sombra - DS
		'sh_001' => 'Sombras',
		'sh_002' => 'Sombra exterior',
		'sh_003' => 'Ancho',
		'sh_004' => 'Margen',
		'sh_005' => 'Angulo',
		'sh_006' => 'Fade',
		'sh_007' => 'Color',
		'sh_008' => 'color de la sombra',
		//------------------------------------------------ -------------------------
		// Bordes redondos - Re
		'br_001' => 'borde',
		'br_002' => 'borde redondeado',
		'br_003' => 'Ancho',
		'br_004' => 'X-radio',
		'br_005' => 'Y-radio',
		'br_006' => 'Color del borde',
		'br_007' => 'si el ancho > 0',
		'br_008' => 'Color',
		//------------------------------------------------ -------------------------
		// Esquinas redondas - RC
		'rc_001' => 'Esquina',
		'rc_002' => 'Esquina redondeada',
		'rc_003 '=> 'X-radio',
		'rc_004' => 'Y-radio',
		'rc_005' => 'Color',
		//------------------------------------------------ -------------------------
		// Elipse - el
		'el_001' => 'Elipse',
		'el_002' => 'Elipse',
		'el_003' => 'Color',
		//------------------------------------------------ -------------------------
		// Caja de herramientas de configuración - SE
		'se_001' => 'Ajustes de caja de herramientas',
		'se_002' => 'Ajustes de caja de herramientas',
		'se_099' => 'Cambiar a la sección',
		//------------------------------------------------ -------------------------
		// Mensajes de error - ER
		'er_001' => 'Error',
		'er_002' => 'No hay imagen seleccionada - por favor seleccione una imagen',
		'er_003' => 'Ancho no es un número',
		'er_004' => 'La altura no es un número',
		'er_005' => 'El borde no es un número',
		'er_006' => 'Espacio horizontal no es un número',
		'er_007' => 'Espacio vertical no es un número',
		'er_008' => 'Haga clic en Aceptar para eliminar la imagen',
		'er_009' => 'Cambiar el nombre de las miniaturas no está permitido! Por favor, cambie el nombre de la imagen principal, si quieres cambiar el nombre de la imagen en miniatura.',
		'er_010' => 'Haga clic en Aceptar para cambiar el nombre a la imagen',
		'er_011' => 'Nuevo nombre está vacío o no ha cambiado!',
		'er_012' => 'Ampliar la imagen no está permitido! Por favor, compruebe AMPLIAR para permitir la ampliación de la imagen. ',
		'er_013' => 'Código de color no válido',
		'er_014' => 'Por favor, escriba el nombre de archivo nuevo!',
		'er_015' => 'Por favor, escriba el nombre de archivo válido!',
		'er_016' => 'La miniatura no está disponible! Por favor, establezca el tamaño de miniatura en el archivo de configuración a fin de tener miniaturas.',
		'er_017' => 'No ha sido seleccionada la imagen de marca de agua!',
		'er_018' => 'No se ha seleccionado la máscara!',
		'er_020' => 'No se ha seleccionado ninguna acción en la caja de herramientas! Por favor, inténtelo de nuevo ...',
		'er_021' => 'Por favor, haga clic en Aceptar para cargar la(s) imagen(es).',
		'er_022' => 'Cargando la imagen - por favor espere ...',
		'er_023' => 'No hay imagen ha sido seleccionada o no el tamaño del archivo ha sido comprobado.',
		'er_024' => 'Archivo',
		'er_025' => 'ya existe! Por favor, haga clic en Aceptar para sobrescribir el archivo ...',
		'er_026' => 'Por favor, escriba el nombre del archivo nuevo!',
		'er_027' => 'La carpeta física no existe',
		'er_028' => 'Ocurrió un error durante la manipulación de archivos. Por favor, inténtelo de nuevo.',
		'er_029' => 'Tipo de archivo de imagen incorreco',
		'er_030' => 'No se pudo eliminar! Por favor, inténtelo de nuevo.',
		'er_031' => 'Sobreescribir',
		'er_032' => 'No se encontro ajustes de configuración de filtros',
		'er_033' => 'No se encontraron ajustes de configuración de Herramientas',
		'er_034' => 'El valor superior no es permitido! el valor Max. es',
		'er_035' => 'El valor izquierdo no es permitido! el valor Max. es',
		'er_036' => 'dimensión del recorte es más grande que la dimensión de origen',
		'er_037' => 'No está disponible en el modo "standalone"!',
		'er_038' => 'La vista previa de tamaño completo sólo funciona para las imágenes más grandes que el tamaño de vista previa!',
		'er_040' => 'No se ha  seleccionado superposición de imágenes!',
		'er_041' => 'No se pudo cambiar el nombre! Por favor, inténtelo de nuevo. ',
		'er_042' => 'No se pudo crear el directorio! Por favor, inténtelo de nuevo. ',
		'er_043' => 'La ampliación no está permitida!',
		'er_044' => 'Error construyendo la lista de imágenes',
		),
		// 'er_099' => '',
	
		//------------------------------------------------ -------------------------
		// Selector de color

		'colorpicker' => array (
		'title' => 'Selector de color',
		'ok' => 'OK',
		'cancelar' => 'Cancelar',
		),
		//------------------------------------------------ -------------------------
		// Símbolos
		'símbolos' => array (
		'title' => 'Símbolos',
		'ok' => 'OK',
		'cancelar' => 'Cancelar',
		),
	
		//------------------------------------------------ -------------------------
		// Ejemplos
		'ejemplos' => array (
		'ex_001' => 'ejemplos',
		'ex_002' => 'ejemplos iManager',
		'ex_003' => 'Cerrar', 
		),
	
	);
?>